### 1. Cream User 1 (Alex)
POST http://localhost:8080/api/users
Content-Type: application/json

{ "name": "Alex", "email": "alex@jedi.com" }

### 2. Cream User 2 (Mihnea)
POST http://localhost:8080/api/users
Content-Type: application/json

{ "name": "Mihnea", "email": "mihnea@jedi.com" }

### 3. Adaugam o carte in catalog (cu 1 singur exemplar fizic)
POST http://localhost:8080/api/books
Content-Type: application/json

{ "title": "Spring Boot Mastery", "copies": 1 }

### ==============================================================
### ATENTIE: Copiaza ID-ul cartii create la pasul 3 si pune-l in link-urile de mai jos!
### ==============================================================

### 4. Alex IMPRUMUTA cartea (Stocul devine 0)
POST http://localhost:8080/api/books/69c3123637e67e7f63f00416/borrow
Content-Type: application/json

{ "userEmail": "alex@jedi.com" }

### 5. Mihnea incearca si el (Va primi EROARE 409 controlata)
POST http://localhost:8080/api/books/69c3123637e67e7f63f00416/borrow
Content-Type: application/json

{ "userEmail": "mihnea@jedi.com" }

### 6. Mihnea da RESERVE (Intra in coada de asteptare)
POST http://localhost:8080/api/books/69c3123637e67e7f63f00416/reserve
Content-Type: application/json

{ "userEmail": "mihnea@jedi.com" }

### 7. Alex RETURNEAZA cartea (Primeste XP, iar cartea se duce la Mihnea)
POST http://localhost:8080/api/books/69c3123637e67e7f63f00416/return
Content-Type: application/json

{ "userEmail": "alex@jedi.com" }