pipeline {
    agent any

    tools {
        jdk 'jdk21'
        gradle 'gradle-8'
    }

    environment {
        CI = 'true'
        DOCKER_HUB_USERNAME = 'calinfrunzeanu'
        DOCKER_PASSWORD = credentials('docker_password')
        GITHUB_TOKEN = credentials('github_token')
    }

    stages {
        stage('Build') {
            steps {
                script {
                    env.TESTCONTAINERS_HOST_OVERRIDE = sh(
                        script: "ip route | grep default | cut -d' ' -f3",
                        returnStdout: true
                    ).trim()

                    echo "Testcontainers host override: ${env.TESTCONTAINERS_HOST_OVERRIDE}"
                }
                sh './gradlew clean build -x test'
            }
        }

        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }

        stage('Version & Tag') {
            steps {
                script {
                    sh 'git fetch --tags'

                    env.MAJOR_VERSION = sh(
                        script: 'git tag | sort -V | tail -1 | cut -d . -f 1',
                        returnStdout: true
                    ).trim()

                    env.MINOR_VERSION = sh(
                        script: 'git tag | sort -V | tail -1 | cut -d . -f 2',
                        returnStdout: true
                    ).trim()

                    env.PATCH_VERSION = sh(
                        script: 'git tag | sort -V | tail -1 | cut -d . -f 3',
                        returnStdout: true
                    ).trim()

                    if (!env.MAJOR_VERSION || env.MAJOR_VERSION == "") {
                        env.MAJOR_VERSION = "1"
                        env.MINOR_VERSION = "-1"
                        env.PATCH_VERSION = "0"
                    }

                    def minorInt = env.MINOR_VERSION.toInteger()
                    env.IMAGE_TAG = "${env.MAJOR_VERSION}.${minorInt + 1}.${env.PATCH_VERSION}"
                    echo "Building version: ${env.IMAGE_TAG}"
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $DOCKER_HUB_USERNAME/prod-eng-img:$IMAGE_TAG .'
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh '''
                    echo $DOCKER_PASSWORD_PSW | docker login -u $DOCKER_HUB_USERNAME --password-stdin
                    docker push $DOCKER_HUB_USERNAME/prod-eng-img:$IMAGE_TAG
                '''
            }
        }

        stage('Tag Release') {
            steps {
                sh '''
                    git tag $IMAGE_TAG
                    git push https://$GITHUB_TOKEN_PSW@github.com/prod-eng-lab1-1/service.git $IMAGE_TAG
                '''
            }
        }
    }

    post {
        always {
            sh 'docker logout'
        }
    }
}
